name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'

      - name: Build
        shell: powershell
        run: .\build.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoBoxBot
          path: out/MoBoxBot.jar
